version: "3"
services:
  expo_sample:
    container_name: test
    tty: true
    build: .
    volumes:
      - .:/home/app
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
